FROM openjdk:18-jdk-alpine
MAINTAINER baeldung.com
COPY target/algorithmservice-0.0.1-SNAPSHOT.jar algorithmservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/algorithmservice-0.0.1-SNAPSHOT.jar"]